// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Raijin.SatSolver.Infrastructure.Persistence;

#nullable disable

namespace Raijin.SatSolver.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SatSolverDbContext))]
    [Migration("20260405153006_AddedCreatedAt")]
    partial class AddedCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Raijin.SatSolver.Infrastructure.Persistence.Models.SatProblemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Satisfiability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<int[]>("Solution")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("SolvingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("SatProblems");
                });

            modelBuilder.Entity("Raijin.SatSolver.Infrastructure.Persistence.Models.SatProblemModel", b =>
                {
                    b.OwnsMany("Raijin.SatSolver.Infrastructure.Persistence.Models.ClauseModel", "Clauses", b1 =>
                        {
                            b1.Property<Guid>("SatProblemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.PrimitiveCollection<int[]>("Literals")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.HasKey("SatProblemId", "Id");

                            b1.ToTable("ClauseModel");

                            b1.WithOwner()
                                .HasForeignKey("SatProblemId");
                        });

                    b.Navigation("Clauses");
                });
#pragma warning restore 612, 618
        }
    }
}
