// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Raijin.SatSolver.Infrastructure.Persistence;

#nullable disable

namespace Raijin.SatSolver.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SatSolverDbContext))]
    partial class SatSolverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Raijin.SatSolver.Infrastructure.Persistence.Models.SatProblemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Dimacs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Satisfiability")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<int[]>("Solution")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("SatProblems");
                });
#pragma warning restore 612, 618
        }
    }
}
