using Raijin.ProblemSolvingService.Application.Features.CommonSat.Dtos;

namespace Raijin.ProblemSolvingService.Application.Features.CommonSat.Commands.SolveSatExpression;

public sealed record SolveSatExpressionCommandResult(SolvingStatusDto SolvingStatus, List<NamedSatVariableAssignmentDto> VariableAssignments);