// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Raijin.CombinatoricsService.Infrastructure.Persistence;

#nullable disable

namespace Raijin.CombinatoricsService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CombinatoricsServiceDbContext))]
    [Migration("20260325024515_ReplacedSolutionForBooleanProblemWithJsonb")]
    partial class ReplacedSolutionForBooleanProblemWithJsonb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.BooleanProblemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Satisfiability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, bool>>("Solution")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("BooleanProblems");
                });

            modelBuilder.Entity("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.CombinatoricProblemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Constraints")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Satisfiability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("Solution")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("CombinatoricProblems");
                });

            modelBuilder.Entity("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.CombinatoricProblemModel", b =>
                {
                    b.OwnsMany("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.DecisionVariableModel", "DecisionVariables", b1 =>
                        {
                            b1.Property<Guid>("CombinatoricProblemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string[]>("States")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("CombinatoricProblemId", "Id");

                            b1.ToTable("DecisionVariableModel");

                            b1.WithOwner()
                                .HasForeignKey("CombinatoricProblemId");
                        });

                    b.Navigation("DecisionVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
