// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Raijin.CombinatoricsService.Infrastructure.Persistence;

#nullable disable

namespace Raijin.CombinatoricsService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CombinatoricsServiceDbContext))]
    partial class CombinatoricsServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.ProblemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<JsonDocument>("Instance")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProblemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<JsonDocument>("Solution")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.ProblemModel", b =>
                {
                    b.OwnsOne("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.SatEncodingModel", "SatEncoding", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Dimacs")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ProblemId")
                                .HasColumnType("uuid");

                            b1.Property<JsonDocument>("VariableMap")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.HasKey("Id");

                            b1.HasIndex("ProblemId")
                                .IsUnique();

                            b1.ToTable("SatEncodings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProblemId");
                        });

                    b.OwnsOne("Raijin.CombinatoricsService.Infrastructure.Persistence.Models.SatRunModel", "SatRun", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<int[]>("Assignment")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ProblemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Satisfiability")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProblemId")
                                .IsUnique();

                            b1.ToTable("SatRuns", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProblemId");
                        });

                    b.Navigation("SatEncoding");

                    b.Navigation("SatRun");
                });
#pragma warning restore 612, 618
        }
    }
}
